import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#e5eeff',
        'primary-fixed': '#dae2ff',
        'surface-dim': '#cbdbf5',
        'tertiary-container': '#00618b',
        'inverse-surface': '#213145',
        secondary: '#545f73',
        'surface-bright': '#f8f9ff',
        'on-secondary': '#ffffff',
        'surface-container-high': '#dce9ff',
        'on-primary-container': '#c4d2ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-tertiary-container': '#a7d9ff',
        surface: '#f8f9ff',
        'on-surface-variant': '#434654',
        'on-primary': '#ffffff',
        'surface-variant': '#d3e4fe',
        'surface-container-low': '#eff4ff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#0040a2',
        'on-secondary-container': '#586377',
        'on-tertiary-fixed-variant': '#004c6e',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#bcc7de',
        'secondary-fixed': '#d8e3fb',
        'primary-container': '#0052cc',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#3c475a',
        'on-primary-fixed': '#001848',
        'secondary-container': '#d5e0f8',
        'on-background': '#0b1c30',
        'inverse-on-surface': '#eaf1ff',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'outline-variant': '#c3c6d6',
        outline: '#737685',
        background: '#f8f9ff',
        'primary-fixed-dim': '#b2c5ff',
        'inverse-primary': '#b2c5ff',
        tertiary: '#004869',
        primary: '#003d9b',
        'on-tertiary-fixed': '#001e2f',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#89ceff',
        'surface-tint': '#0c56d0',
        'on-secondary-fixed': '#111c2d',
        'tertiary-fixed': '#c9e6ff',

        // Aliases for existing app pages that use camelCase utility names.
        onSurface: '#0b1c30',
        onSurfaceVariant: '#434654',
        primaryContainer: '#0052cc',
        surfaceTint: '#0c56d0',
        surfaceContainerHigh: '#dce9ff',
        surfaceContainerHighest: '#d3e4fe',
        surfaceContainerLow: '#eff4ff',
        surfaceDim: '#cbdbf5',
        inverseSurface: '#213145',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      boxShadow: {
        card: '0 10px 30px -12px rgba(12, 86, 208, 0.28)',
      },
    },
  },
  plugins: [],
} satisfies Config
